name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate_docs:
    runs-on: ubuntu-22.04
    env:
      REPO_URL: https://github.com/${{ github.repository }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Building project of my life for Linxdatacenter internship"
          docker build -t linx:latest .